### PR TITLE
working search! fixes #6

### LINKED ISSUE #6: Implement fuzzy search
Everything can be done in `Toolbar.jsx`, please only implement within the `fuzzySearch` method, which takes an object of the form `{email1: user1, email2: user2, ...}` and should return another object filtering out things that don't match.

### PR DESCRIPTION
**Pull request by jaisal1024**
Pleaase check it out and make sure it is fast enough.

### CODE REVIEW

**Comment by jaisal1024** [comment]
Made a big change, all mentors have only 1 mentee now. Refactored the upload and front end code to handle this. In terms of requirements, I confirmed with Gabriel that this is the case -- All mentors have only 1 mentee max.

**Comment by jaisal1024** [comment]
We may also want to add a search on email key. The implementation would need to be changed. But it would be quite easy. This would make it easier to select display the mentee for a certain mentor.

**Comment by jaisal1024** [comment]
Resolves #6

**Comment by danielwatson6** [comment]
Tested

**Pull request merged**
